version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
  dependencies:
    - pip
    - git+https://github.com/HailinPan/npspy.git


sphinx:
  configuration: docs/source/conf.py
