[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "npspy"
authors = [{name = "Hailin Pan", email = "panhailin@genomics.cn"}]
dynamic = ["version=v1.0.0", "description=This is the tutorial for npspy."]
